# db-credentials isimli ClusterSecretStore nesnesi tanımlama dosyası
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: production
spec:
  refreshInterval: "1h" # 1 saatte bir Vault'tan güncellemeleri kontrol et
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-secret # Oluşturulacak yerel Kubernetes Secret adı
    creationPolicy: Owner
  data:
  - secretKey: username # K8s secret içindeki key
    remoteRef:
      key: database/credentials # Vault'taki yol (path)
      property: db_user # Vault içindeki JSON key'i
  - secretKey: password
    remoteRef:
      key: database/credentials
      property: db_pass
