# team-billing-kustomization isimli GitRepository nesnesi tanımlama dosyası
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: team-billing-kustomization
  namespace: flux-system
spec:
  interval: 5m
  # Billing ekibine ait kısıtlı ServiceAccount'u kullanarak deploy et:
  serviceAccountName: billing-deployment-sa
  path: "./apps/billing"
  sourceRef:
    kind: GitRepository
    name: app-source-repo
