apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cattle-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: cattle-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
      - name: rancher
        image: rancher/rancher:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: cattle-keys-volume
          mountPath: /etc/rancher/ssl
          readOnly: true
        env:
        - name: CATTLE_BOOTSTRAP_PASSWORD
          value: "admin"
      volumes:
      - name: cattle-keys-volume
        secret:
          secretName: tls-rancher-ingress
---
apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-system
spec:
  selector:
    app: rancher
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443
  type: NodePort
