# 🔝 PriorityClass Örneği

```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-apps
value: 1000000                        # Yüksek sayı = Yüksek öncelik
globalDefault: false
preemptionPolicy: PreemptLowerPriority # Düşük öncelikli pod'ları çıkarabilir
description: "Kritik üretim servisleri için yüksek öncelik sınıfı."
```
