apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # Rook tarafından desteklenen Ceph imajı sürümü
    image: quay.io/ceph/ceph:v18.2.0
    allowUnsupported: false
  
  dataDirHostPath: /var/lib/rook # Düğümlerde metadata tutulacak yer
  
  mon:
    # Yüksek erişilebilirlik (HA) için 3 Monitor (mon) node gerekir
    count: 3
    allowMultiplePerNode: false
  
  dashboard:
    enabled: true # Ceph web yönetim paneli aktif edilsin
    ssl: true
  
  crashCollector:
    disable: false
  
  storage:
    useAllNodes: true   # Kümedeki tüm düğümleri kullan
    useAllDevices: true # Düğümlere takılı olan tüm "BOŞ" (formatlanmamış) diskleri OSD olarak kullan
    # İstenirse spesifik düğümler ve diskler belirtilebilir:
    # nodes:
    #   - name: "worker-node-1"
    #     devices:
    #       - name: "sdb"
    #       - name: "nvme0n1"
