# LGTM (Loki, Grafana, Tempo, Mimir) ve Surekli Profil Cikarma (Pyroscope) Helm Degerleri (values.yaml)
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 3
  storage:
    type: s3
    s3:
      bucketnames: "company-k8s-loki-logs"
      endpoint: "s3.eu-central-1.amazonaws.com"
      region: "eu-central-1"

tempo:
  storage:
    trace:
      backend: s3
      s3:
        bucket: "company-k8s-tempo-traces"
        endpoint: "s3.eu-central-1.amazonaws.com"

pyroscope:
  ebpf:
    enabled: true # cekirdek seviyesinde sifir yukle surekli CPU profil cikarma