apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: web
  name: mypod1
  namespace: test
spec:
  containers:
  - image: nginx:1.27.0
    name: mypod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
