# aws-db-secrets isimli SecretProviderClass nesnesi tanımlama dosyası
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-db-secrets
  namespace: production
spec:
  provider: aws # AWS Secrets Manager Sağlayıcısı
  parameters:
    objects: |
      - objectName: "production/database/credentials" # AWS'deki Secret Adı
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db_user" # Dışarıya çıkacak dosya adı
          - path: "password"
            objectAlias: "db_pass"
