# database-credentials isimli ClusterSecretStore nesnesi tanımlama dosyası
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: production
spec:
  refreshInterval: "1h" # Her saat harici kasadaki şifreyi sorgula ve güncelle
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-secret-k8s # Kubernetes üzerinde oluşturulacak secret nesnesi
    creationPolicy: Owner
  data:
    - secretKey: db_password
      remoteRef:
        key: secret/data/production/database
        property: password
