# secured-api isimli Deployment nesnesi tanımlama dosyası
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secured-api
  namespace: production
spec:
  replicas: 2
  template:
    spec:
      serviceAccountName: api-service # Workload Identity yetkisine sahip hesap
      containers:
      - name: api
        image: registry.example.com/secured-api:v1.0
        # Çevre Değişkeni Eşleşmesi (Sync modülü aktifse çalışır)
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aws-db-secrets-sync # KEDA/Kubernetes için geçici senkronize edilen secret
              key: db_pass
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store" # Şifrelerin yazılacağı geçici bellek dizini
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-db-secrets" # Tanımladığımız SecretProviderClass
