# kubeconfig isimli Config nesnesi tanımlama dosyası
apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTi...
    server: https://192.168.10.100:6443
  name: prod-cluster
users:
- name: prod-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTi...
    client-key-data: LS0tLS1CRUdJTi...
contexts:
- context:
    cluster: prod-cluster
    user: prod-admin
    namespace: production
  name: prod-context
current-context: prod-context
