# dagitik_izleme_tempo isimli Kubernetes nesnesi tanımlama dosyası
tempo:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  storage:
    trace:
      backend: s3
      s3:
        bucket: company-traces-bucket
        endpoint: minio.storage.svc.cluster.local:9000
        access_key: "MinioAccessKey"
        secret_key: "MinioSecretKey"
        insecure: true
