apiVersion: v1
kind: Namespace
metadata:
  name: web-page
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: farukguler-pv
  namespace: web-page
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany  # nfs, birden fazla pod'un aynı dosyayı okumasına/yazmasına olanak tanır
  nfs:
    path: /nfs/kubedata/farukguler/  # nfs sunucusunda paylaşılan dizin
    server: 192.168.44.145  # nfs sunucusunun IP adresi veya hostname (örnek)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: farukguler-pvc
  namespace: web-page
spec:
  accessModes:
    - ReadWriteMany  # PVC de aynı şekilde birden fazla pod'un erişebilmesi için ReadWriteMany kullanılabilir
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: web-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: farukguler-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: web-page
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
