# azure-keyvault-store isimli SecretStore nesnesi tanımlama dosyası
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: production
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://my-keyvault-2026.vault.azure.net"
      serviceAccountRef:
        name: azure-eso-sa
