# aws-secrets-store isimli SecretStore nesnesi tanımlama dosyası
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: production
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            # AWS IAM rolü iliştirilmiş ServiceAccount
            name: aws-eso-sa
