# backup-local-secret isimli ClusterSecretStore nesnesi tanımlama dosyası
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: backup-local-secret
  namespace: production
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  selector:
    secret:
      name: my-local-app-secret # Kümdeki mevcut local secret
  data:
    - match:
        secretKey: api_token # Hangi key push edilecek
        remoteRef:
          remoteKey: backups/app-api-token # Dışarıda yazılacak yer (Vault path)
