# prometheus-stack isimli HelmRepository nesnesi tanımlama dosyası
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "51.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-repo
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        retention: 30d
