# pod_guvenlik_standartlari isimli PodSecurityConfiguration nesnesi tanımlama dosyası
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "baseline"
      enforce-version: "latest"
      audit: "restricted"
      audit-version: "latest"
      warn: "restricted"
      warn-version: "latest"
    exemptions:
      # Belirli kullanıcı veya namespace'leri muaf tutmak için:
      namespaces:
      - kube-system
      - spire-system
