# dns_sorun_giderme isimli Kubernetes nesnesi tanımlama dosyası
spec:
      policyTypes:
        - Egress
      egress:
        - to:
            - namespaceSelector: {}
              podSelector:
                matchLabels:
                  k8s-app: kube-dns
          ports:
            - protocol: UDP
              port: 53
